#! /usr/bin/env bash
#
# Display Yeelight® bulb status with nice icons
#   

STATUS_FILE="$HOME/.config/ylight/ylight.status"

get_status() {
    local light_status power bright timer _status

    light_status="$(ylight -s)"

	HOST="$(awk '/host/ {print $2}' <<< "$light_status")"
	PORT="$(awk '/port/ {print $2}' <<< "$light_status")"
    power="$(awk '/power/ {print $2}' <<< "$light_status")"
    bright="$(awk '/brightness/ {print $2}' <<< "$light_status")"
    timer="$(awk '/timer/ {print $2}' <<< "$light_status")"

    if [[ $power ]]; then
		[[ $power == "on" ]] && _status=" $bright" || _status=""
		[[ $timer ]] && _status+="   $timer mn"
    else
		_status="[]"
    fi

    echo "$_status" > "$STATUS_FILE"
}

listen() {
    while read -r; do
		get_status
    done < <(netcat "$HOST" "$PORT")
}

get_status
listen
